###############
# General Config
#

baseURL = "https://mmk2410.org/"
languageCode = "en-us"
languageName = "English"
defaultContentLanguge = "en"
title = "Marcel Kapfer"
theme = "nextDESIGN"

# Enable the possibility to use .GitInfo
enableGitInfo = true

###############
# RSS
#

# Only put the last ten entrys in the RSS feed
rssLimit = 10

###############
# Author
#

[author]
name = "Marcel Kapfer"

###############
# Permalinks
#

[permalinks]
blog = "/:year/:month/:day/:title/"
quotes = "/:year/:month/:day/:title/"

###############
# Related Content
#

[related]
includeNewer = true

###############
# Additional menu entries
#

[menu]

[[menu.main]]
identifier = "composing"
name = "Composing"
weight = 5
url = "https://marcel-kapfer.de"

###############
# Further paramters
#

[params]

copyrighthtml = "2020 (c) Marcel Kapfer<br>Content licensed under CC-BY-SA 4.0"
imprinttext = "Impressum und Datenschutz"
giturl = "https://git.mmk2410.org/mmk2410/mmk2410.org"

[params.social]
mastodon = "https://fosstodon.org/@mmk2410"
gitlab = "https://gitlab.com/mmk2410"
gitea = "https://git.mmk2410.org/mmk2410"

[params.comment]
commentmail = "comment(at)mmk2410(dot)org"

###############
# Markup
#

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

###############
# Privacy
#

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
