title: Site

columns:
  main:
    width: 2/3
    sections:
      pages:
        type: pages
      fields:
        type: fields
        fields:
          menu:
            type: structure
            fields:
              title:
                type: text
                label: Title
              link:
                type: link
                label: Link
                options:
                  - page
                  - url
          footerMenu:
            type: pages
            label: Footer Menu

  sidebar:
    width: 1/3
    sections:
      articles_draft:
        extends: sections/articles
        label: Draft Articles
        status: draft
        parent: site.find("blog")
        layout: list
        limit: 5
      articles_review:
        extends: sections/articles
        label: In Review Articles
        status: unlisted
        parent: site.find("blog")
        layout: list
        limit: 5
      articles_published:
        extends: sections/articles
        label: Published Articles
        status: listed
        parent: site.find("blog")
        layout: list
        limit: 5
      metadata:
        type: fields
        fields:
          author:
            type: text
          authorEmail:
            type: email
          description:
            type: text
          keywords:
            type: tags
          fediverseHandle:
            label: Fediverse Handle
            type: text
